{
 "title": "Interface Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Device_name",
    "label": "Device name",
    "query": "SHOW TAG VALUES WITH KEY = \"source\""
   },
   {
    "name": "Interface_name",
    "label": "Interface",
    "query": "SHOW TAG VALUES WITH KEY = \"interface_name\""
   }
  ]
 },
 "panels": [
  { "title": "Interface status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Admin status",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "$tag_source - $tag_interface_name",
     "groupBy": [
      { "params": [ "interface_name::tag" ], "type": "tag" },
      { "params": [ "source::tag" ], "type": "tag" }
     ],
     "measurement": "srl_if_admin_state",
     "select": [
      [
       {
        "params": [
         "/srl_nokia-interfaces:interface/admin-state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=~", "value": "/^$Device_name$/" },
      { "condition": "AND", "key": "interface_name::tag", "operator": "=~", "value": "/^$Interface_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Oper status",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "alias": "$tag_source - $tag_interface_name",
     "groupBy": [
      { "params": [ "interface_name::tag" ], "type": "tag" },
      { "params": [ "source::tag" ], "type": "tag" }
     ],
     "measurement": "srl_if_oper_state",
     "select": [
      [
       {
        "params": [
         "/srl_nokia-interfaces:interface/oper-state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=~", "value": "/^$Device_name$/" },
      { "condition": "AND", "key": "interface_name::tag", "operator": "=~", "value": "/^$Interface_name$/" }
     ]
    }
   ]
  },
  { "title": "Traffic Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Traffic Rate IN",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "$tag_source - $tag_interface_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface_name::tag" ], "type": "tag" },
      { "params": [ "source::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "srl_if_traffic_rate",
     "select": [
      [
       {
        "params": [
         "/srl_nokia-interfaces:interface/traffic-rate/in-bps"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=~", "value": "/^$Device_name$/" },
      { "condition": "AND", "key": "interface_name::tag", "operator": "=~", "value": "/^$Interface_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Traffic Rate OUT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "$tag_source - $tag_interface_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface_name::tag" ], "type": "tag" },
      { "params": [ "source::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "srl_if_traffic_rate",
     "select": [
      [
       {
        "params": [
         "/srl_nokia-interfaces:interface/traffic-rate/out-bps"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=~", "value": "/^$Device_name$/" },
      { "condition": "AND", "key": "interface_name::tag", "operator": "=~", "value": "/^$Interface_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors IN",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "$tag_source - $tag_interface_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "interface_name::tag" ], "type": "tag" },
        { "params": [ "source::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "port_stats",
       "select": [
        [
         {
          "params": [
           "/interfaces/interface/state/counters/in-errors"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "source::tag", "operator": "=~", "value": "/^$Device_name$/" },
        { "condition": "AND", "key": "interface_name::tag", "operator": "=~", "value": "/^$Interface_name$/" }
       ]
      }
     ]
    },
    {
     "title": "Errors OUT",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "$tag_source - $tag_interface_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "interface_name::tag" ], "type": "tag" },
        { "params": [ "source::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "port_stats",
       "select": [
        [
         {
          "params": [
           "/interfaces/interface/state/counters/out-errors"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "source::tag", "operator": "=~", "value": "/^$Device_name$/" },
        { "condition": "AND", "key": "interface_name::tag", "operator": "=~", "value": "/^$Interface_name$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}