{
 "title": "Routing Flux",
 "time": { "from": "2024-10-16T14:59:50.707Z", "to": "2024-10-16T16:59:50.709Z" },
 "templating": {
  "list": [
   {
    "name": "Device_name",
    "label": "Device",
    "query": {
     "query": "SHOW TAG VALUES WITH KEY = \"source\""
    }
   },
   {
    "name": "network_instance",
    "label": "Network instance",
    "query": {
     "query": "SHOW TAG VALUES WITH KEY=\"network-instance_name\""
    }
   },
   {
    "name": "next_hop_group_index",
    "query": {
     "query": "SHOW TAG VALUES WITH KEY = \"next-hop-group_index\""
    }
   },
   {
    "name": "next_hop_index",
    "query": {
     "query": "SHOW TAG VALUES WITH KEY = \"next-hop_index\""
    }
   }
  ]
 },
 "panels": [
  {
   "title": "IPv4 route changes",
   "type": "table",
   "description": "Changes within selected time range",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "srl_ipv4_route_table",
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"srl_ipv4_route_table\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/srl_nokia-network-instance:network-instance/route-table/srl_nokia-ip-route-tables:ipv4-unicast/route/preference\")",
     "select": [
      [
       {
        "params": [
         "/srl_nokia-network-instance:network-instance/route-table/srl_nokia-ip-route-tables:ipv4-unicast/route/metric"
        ],
        "type": "field"
       }
      ],
      [
       {
        "params": [
         "/srl_nokia-network-instance:network-instance/route-table/srl_nokia-ip-route-tables:ipv4-unicast/route/active"
        ],
        "type": "field"
       }
      ],
      [
       { "params": [ "route_ipv4-prefix" ], "type": "field" }
      ],
      [
       {
        "params": [
         "/srl_nokia-network-instance:network-instance/route-table/srl_nokia-ip-route-tables:ipv4-unicast/route/next-hop-group"
        ],
        "type": "field"
       }
      ],
      [
       {
        "params": [
         "/srl_nokia-network-instance:network-instance/route-table/srl_nokia-ip-route-tables:ipv4-unicast/route/preference"
        ],
        "type": "field"
       }
      ],
      [
       {
        "params": [
         "/srl_nokia-network-instance:network-instance/route-table/srl_nokia-ip-route-tables:ipv4-unicast/route/next-hop-group-network-instance"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=~", "value": "/^$Device_name$/" },
      { "condition": "AND", "key": "network-instance_name::tag", "operator": "=~", "value": "/^$network_instance$/" }
     ]
    }
   ]
  },
  {
   "title": "NH Groups",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "measurement": "srl_nh_groups",
     "query": "SELECT \"/srl_nokia-network-instance:network-instance/route-table/srl_nokia-ip-route-tables:ipv4-unicast/route/metric\", \"/srl_nokia-network-instance:network-instance/route-table/srl_nokia-ip-route-tables:ipv4-unicast/route/active\", \"route_ipv4-prefix \" FROM \"srl_ipv4_route_table\" WHERE $timeFilter",
     "select": [
      [
       {
        "params": [
         "/srl_nokia-network-instance:network-instance/route-table/srl_nokia-ip-route-tables:next-hop-group/next-hop/next-hop"
        ],
        "type": "field"
       }
      ],
      [
       { "params": [ "next-hop-group_index" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=~", "value": "/^$Device_name$/" },
      { "condition": "AND", "key": "network-instance_name::tag", "operator": "=~", "value": "/^$network_instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Next-hops",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "measurement": "srl_next_hops",
     "query": "SELECT \"/srl_nokia-network-instance:network-instance/route-table/srl_nokia-ip-route-tables:ipv4-unicast/route/metric\", \"/srl_nokia-network-instance:network-instance/route-table/srl_nokia-ip-route-tables:ipv4-unicast/route/active\", \"route_ipv4-prefix \" FROM \"srl_ipv4_route_table\" WHERE $timeFilter",
     "select": [
      [
       {
        "params": [
         "/srl_nokia-network-instance:network-instance/route-table/srl_nokia-ip-route-tables:next-hop/ip-address"
        ],
        "type": "field"
       }
      ],
      [
       { "params": [ "next-hop_index" ], "type": "field" }
      ],
      [
       {
        "params": [
         "/srl_nokia-network-instance:network-instance/route-table/srl_nokia-ip-route-tables:next-hop/subinterface"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=~", "value": "/^$Device_name$/" },
      { "condition": "AND", "key": "network-instance_name::tag", "operator": "=~", "value": "/^$network_instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Number of IPv4 unicast active routes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "srl_ipv4_routes",
     "select": [
      [
       {
        "params": [
         "/srl_nokia-network-instance:network-instance/route-table/srl_nokia-ip-route-tables:ipv4-unicast/statistics/active-routes"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=~", "value": "/^$Device_name$/" },
      { "condition": "AND", "key": "network-instance_name::tag", "operator": "=~", "value": "/^$network_instance$/" }
     ]
    }
   ]
  }
 ]
}